#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
# SinCity — Render.com Startup Script
# Generates wp-config.php from env vars, then launches services.
# ═══════════════════════════════════════════════════════════════════════

set -e

# ─── Step 1: Detect environment ────────────────────────────
if [ -z "$RENDER" ]; then
    echo "⚠ RENDER env var not set — assuming local/dev"
fi

echo "→ Render startup: generating wp-config.php"

# ─── Step 2: Generate wp-config.php ────────────────────────
WP_CONFIG="/var/www/html/wp-config.php"

if [ ! -f "$WP_CONFIG" ]; then
    cat > "$WP_CONFIG" << 'WPEOF'
<?php
/**
 * SinCity — wp-config.php
 * Auto-generated by Render startup script from environment variables.
 * DO NOT EDIT — changes will be overwritten on restart.
 */

// ─── Database ─────────────────────────────────────────────
define('DB_NAME',     getenv('DB_NAME')     ?: 'sincity');
define('DB_USER',     getenv('DB_USER')     ?: 'sincity');
define('DB_PASSWORD', getenv('DB_PASSWORD') ?: '');
define('DB_HOST',     getenv('DB_HOST')     ?: 'localhost');
define('DB_CHARSET',  'utf8mb4');
define('DB_COLLATE',  '');

$table_prefix = getenv('WP_TABLE_PREFIX') ?: 'sc_';

// ─── URLs ─────────────────────────────────────────────────
define('WP_HOME',    getenv('WP_HOME')    ?: 'http://localhost');
define('WP_SITEURL', getenv('WP_SITEURL') ?: 'http://localhost');

// ─── Security salts (auto-generated on first deploy) ───────
define('AUTH_KEY',         getenv('AUTH_KEY')         ?: 'replace-me');
define('SECURE_AUTH_KEY',  getenv('SECURE_AUTH_KEY')  ?: 'replace-me');
define('LOGGED_IN_KEY',    getenv('LOGGED_IN_KEY')    ?: 'replace-me');
define('NONCE_KEY',        getenv('NONCE_KEY')        ?: 'replace-me');
define('AUTH_SALT',        getenv('AUTH_SALT')        ?: 'replace-me');
define('SECURE_AUTH_SALT', getenv('SECURE_AUTH_SALT') ?: 'replace-me');
define('LOGGED_IN_SALT',   getenv('LOGGED_IN_SALT')   ?: 'replace-me');
define('NONCE_SALT',       getenv('NONCE_SALT')       ?: 'replace-me');

// ─── Performance ──────────────────────────────────────────
define('WP_CACHE',       false); // No persistent cache on free tier
define('WP_MEMORY_LIMIT', '128M');
define('WP_MAX_MEMORY_LIMIT', '256M');

// ─── Security ─────────────────────────────────────────────
define('DISALLOW_FILE_EDIT',  true);
define('DISALLOW_FILE_MODS',  true); // Prevent plugin/theme install from admin
define('FORCE_SSL_ADMIN',     getenv('FORCE_SSL') ? true : false);
define('WP_AUTO_UPDATE_CORE', false);

// ─── Render-specific ──────────────────────────────────────
define('WP_CONTENT_DIR',    '/var/www/html/wp-content');
define('WP_CONTENT_URL',    WP_HOME . '/wp-content');
define('UPLOADS',           'wp-content/uploads');

// ─── Debug ────────────────────────────────────────────────
define('WP_DEBUG',          getenv('WP_DEBUG') === 'true');
define('WP_DEBUG_LOG',      false);
define('WP_DEBUG_DISPLAY',  false);

// ─── CRON ─────────────────────────────────────────────────
// On Render free tier, use cron-job.org instead of WP-Cron
define('DISABLE_WP_CRON',   getenv('DISABLE_WP_CRON') === 'true');

// ─── Absolute path ────────────────────────────────────────
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}
require_once ABSPATH . 'wp-settings.php';
WPEOF

    echo "✓ wp-config.php generated from environment variables"
else
    echo "✓ wp-config.php already exists — skipping"
fi

# ─── Step 3: Create uploads directory if missing ──────────
mkdir -p /var/www/html/wp-content/uploads
chown -R www-data:www-data /var/www/html/wp-content

# ─── Step 4: Start PHP-FPM ────────────────────────────────
echo "→ Starting PHP-FPM..."
php-fpm -D
echo "✓ PHP-FPM started"

# ─── Step 5: Test PHP-FPM socket ──────────────────────────
sleep 1
if [ -S /var/run/php/php8.2-fpm.sock ]; then
    echo "✓ PHP-FPM socket ready"
else
    echo "⚠ PHP-FPM socket not found — checking /run/..."
    ls -la /run/php/ 2>/dev/null || echo "No /run/php/ dir"
fi

# ─── Step 6: Start Nginx in foreground ────────────────────
echo "→ Starting Nginx..."
nginx -g 'daemon off;'
